# NumPy Indexing

In [2]:
import numpy as np

In [3]:
# array between 0 and 10
arr = np.arange(11) 

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

np.int64(8)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Broadcasting

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
# note that the slice affects the original array as well
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
# to copy an array, use the .copy() method
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2 dimentioanl array (matrix)

Indexing exmples <br/>
mat[row, col]<br/>
mat[row][col]<br/>

In [17]:
mat = np.array([[5,10,15],
                [20,25,30],
                [35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
mat[0]

array([ 5, 10, 15])

In [19]:
mat[2]

array([35, 40, 45])

In [20]:
mat[1][1]

np.int64(25)

In [21]:
mat[1, 1]

np.int64(25)

## 2D Array Slicing

In [22]:
# pick the row then the column - upto row 2 and all columns after column 1
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

# Conditional Selection

In [23]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

## Parsing a boolian array into an arry

In [25]:
bull_arr = arr > 4
arr[bull_arr]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
# Commonly done in one line using conditional selection
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])